services:
  caddy:
    image: serfriz/caddy-crowdsec:latest
    container_name: caddy
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - CROWDSEC_API_KEY=${CROWDSEC_API_KEY}
      - CADDY_ADMIN=:2019 #Needed if using dashboard
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
      - "2019:2019" #Needed if using dashboard
    volumes:
      - './Caddyfile:/etc/caddy/Caddyfile:ro'
      - config:/config
      - data:/data
      - ./logs:/var/log/caddy
    networks:
      - caddy

networks:
  caddy:
    name: caddy

volumes:
    config:
    data:
