services:
  crowdsec:
    image: crowdsecurity/crowdsec:latest
    container_name: crowdsec
    environment:
      COLLECTIONS: "crowdsecurity/linux crowdsecurity/caddy crowdsecurity/appsec-generic-rules crowdsecurity/appsec-virtual-patching LePresidente/authelia"
    ports:
      - "8080:8080"
    volumes:
      - ./config/acquis.yaml:/etc/crowdsec/acquis.yaml
      - ./config:/etc/crowdsec/
      - crowdsec-db:/var/lib/crowdsec/data/
      - ../caddy/logs/:/var/log/caddy/:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - caddy
    restart: unless-stopped

networks:
  caddy:
    external: true

volumes:
  crowdsec-db:
